modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/TwistedGate/ImmersivePetroleum/issues"
license="All rights reserved"

[[mods]] #mandatory
	modId="immersivepetroleum"
	version="${file.jarVersion}"
	displayName="Immersive Petroleum"
	displayURL="https://minecraft.curseforge.com/projects/immersive-petroleum"
	authors="Flaxbeard and Maintained by TwistedGate. Updated to this version by ArcAnc"
	description="Adds oil and oil processing features to Immersive Engineering."
	logoFile="logo.png"
	#updateJSONURL=""
	#credits=""

[[dependencies.immersivepetroleum]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[1.20.1-10.1.0-171,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="forge"
	mandatory=true
	versionRange="[47.2.23,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20.1]"
	ordering="NONE"
	side="BOTH"
